

export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const SETUP_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const SETUP_USER_ERROR = 'LOGIN_USER_ERROR'
export const SETUP_USER_BEGIN = 'LOGIN_USER_BEGIN'

export const LOGOUT_USER = "LOGOUT_USER";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const TOGGLE_RIGHT_SIDEBAR = "TOGGLE_RIGHT_SIDEBAR"


export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const SEND_CARTITEMS_SUCCESS = 'SEND_CARTITEMS_SUCCESS'; 
export const SEND_CARTITEMS_BEGIN = 'SEND_CARTITEMS_BEGIN';  
export const SEND_CARTITEMS_ERROR = 'SEND_CARTITEMS_ERROR';  

export const UPDATE_CARTITEMS_BEGIN = 'UPDATE_CARTITEMS_BEGIN'
export const UPDATE_CARTITEMS_ERROR = 'UPDATE_CARTITEMS_ERROR'
export const UPDATE_CARTITEMS_SUCCESS = 'UPDATE_CARTITEMS_SUCCESS'

export const GET_CARTITEMS_SUCCESS = 'GET_CARTITEMS_SUCCESS';
export const GET_CARTITEMS_BEGIN = 'GET_CARTITEMS_BEGIN';
export const GET_CARTITEMS_ERROR= 'GET_CARTITEMS_ERROR';

export const DELETE_CARTITEMS_BEGIN= 'DELETE_CARTITEMS_BEGIN';
export const DELETE_FAVITEMS_BEGIN = 'DELETE_FAVITEMS_BEGIN';

export const SEND_FAVITEMS_SUCCESS = 'SEND_FAVITEMS_SUCCESS'; 
export const SEND_FAVITEMS_BEGIN = 'SEND_FAVITEMS_BEGIN'; 
export const SEND_FAVITEMS_ERROR = 'SEND_FAVITEMS_ERROR'; 

export const GET_FAVITEMS_BEGIN = 'GET_FAVITEMS_BEGIN'; 
export const GET_FAVITEMS_SUCCESS = 'GET_FAVITEMS_SUCCESS'; 
export const GET_FAVITEMS_ERROR = 'GET_FAVITEMS_ERROR'; 

export const UPDATE_FAVITEMS_BEGIN = 'UPDATE_FAVITEMS_BEGIN'; 
export const UPDATE_FAVITEMS_SUCCESS = 'UPDATE_FAVITEMS_SUCCESS'; 
export const UPDATE_FAVITEMS_ERROR = 'UPDATE_FAVITEMS_ERROR'; 

