// import i from '../../src/assets/images'
const filter = [
  {
    id: 0,
    name: "sort-container",
    btnText: "sort",
    btn: "sort-btn",
    labelName: "sort-cntr",
    options: [
      "best Match",
      "price: low to high",
      "price:high to low",
      "newest",
      "customer rating",
      "Name",
      "most popular",
      "width",
      "height",
      "length",
    ],
  },
  {
    id: 1,
    name: "size-container",
    btnText: "size",
    btn: "size-btn",
    labelName: "size-cntr",
    options: ["x-small", "small", "medium", "large", "x-large"],
  },
  {
    id: 2,
    name: "color-container",
    btnText: "color",
    btn: "color-btn",
    labelName: "size-cntr",
    options: ["yellow", "green", "blue", "red", "black", "white"],
  },
  {
    id: 3,
    name: "price-container",
    btnText: "price",
    btn: "price-btn",
    labelName: "price-cntr",
    options: ["$0-$5", "$5-$10", "$10-$20", "$20-$50", "$50-$100", "$100+"],
  },
  {
    id: 4,
    name: "category-container",
    btn: "category-btn",
    btnText: "category",
    labelName: "category-cntr",
    options: ["kitchen", "bathroom", "bedroom", "living", "organization"],
  },
  {
    id: 5,
    name: "features-container",
    btn: "features-btn",
    btnText: "features",
    labelName: "features-cntr",
    options: ["kitchen", "bathroom", "bedroom", "living", "organization"],
  },
  {
    id: 6,
    name: "All-filters-btn",
    btn: "all-filters-btn",
    btnText: "All-filters",
    labelName: "all-filters-cntr",
    options: ["kitchen", "bathroom", "bedroom", "living", "organization"],
    button: "IoIosOptions",
  },
];
export default filter;
